//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace senasistencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHA
    {
        public int ID_Ficha { get; set; }
        public Nullable<int> Numeroficha { get; set; }
        public string Centro_de_formacion { get; set; }
        public string Sede { get; set; }
        public string Ambiente { get; set; }
        public string Trimestre { get; set; }
        public string Jornada { get; set; }
        public string Instructor { get; set; }
        public Nullable<int> EstadoFicha { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Inactivacion { get; set; }
        public string Aprendiz { get; set; }
    }
}
